### ISSUE TITLE
Execute `./edgecontroller` error

### ISSUE THREAD

**Issue by zhanghongtong** [kubeedge/kubeedge#224] opened 2019-03-12 01:17 UTC
**What happened**:
Execute `./edgecontroller` error

**What you expected to happen**:
 + Set up according to the content of the [document](https://docs.kubeedge.io/en/latest/setup/setup.html).
 + Execute `./edgecontroller` error
```
$ ./edgecontroller
2019/03/11 07:57:30 WARN: empty configurtion from [CommandlineSource]
2019/03/11 07:57:30 WARN: empty configurtion from [MemorySource]
New file source added for configuration: /home/ubuntu/go/src/github.com/kubeedge/kubeedge/cloud/edgecontroller/conf/controller.yamlNew file source added for configuration: /home/ubuntu/go/src/github.com/kubeedge/kubeedge/cloud/edgecontroller/conf/logging.yamlNew file source added for configuration: /home/ubuntu/go/src/github.com/kubeedge/kubeedge/cloud/edgecontroller/conf/modules.yaml/home/ubuntu/go/src/github.com/kubeedge/kubeedge/cloud/edgecontroller/conf/logging.yamllogConfig:&{INFO edgecontroller.log [file stdout] true false  }
2019/03/11 07:57:30 RollingPolicy is empty, use default policy[size]
2019-03-11 07:57:30.059 +00:00 INFO core/module.go:54 module cloudhub registered
2019-03-11 07:57:30.061 +00:00 INFO config/buffer.go:27 update pod status buffer: 1024
2019-03-11 07:57:30.061 +00:00 INFO config/buffer.go:34 Update node status buffer: 1024
2019-03-11 07:57:30.061 +00:00 INFO config/buffer.go:41 query config map buffer: 1024
2019-03-11 07:57:30.061 +00:00 INFO config/buffer.go:48 query secret buffer: 1024
2019-03-11 07:57:30.061 +00:00 INFO config/context.go:28  send module name: cloudhub
2019-03-11 07:57:30.061 +00:00 INFO config/context.go:35 receive module name: controller
2019-03-11 07:57:30.061 +00:00 INFO config/context.go:42 response module name: cloudhub
2019-03-11 07:57:30.061 +00:00 INFO config/kube.go:38 kube master: http://localhost:8080
2019-03-11 07:57:30.061 +00:00 ERROR config/kube.go:41 kube config not set
2019-03-11 07:57:30.061 +00:00 INFO config/kube.go:45 kube config:
2019-03-11 07:57:30.061 +00:00 INFO config/kube.go:52 kube namespace:
2019-03-11 07:57:30.061 +00:00 INFO config/kube.go:59 kube content type: application/vnd.kubernetes.protobuf
2019-03-11 07:57:30.061 +00:00 INFO config/kube.go:66 kube QPS: 5.000000
2019-03-11 07:57:30.061 +00:00 INFO config/kube.go:73 kube burst: 10
2019-03-11 07:57:30.062 +00:00 INFO config/kube.go:80 kube update frequency: 10s
2019-03-11 07:57:30.062 +00:00 INFO config/load.go:27 update pod status workers: 1
2019-03-11 07:57:30.062 +00:00 INFO config/load.go:34 update node status workers: 1
2019-03-11 07:57:30.062 +00:00 INFO config/load.go:41 query config map workers: 4
2019-03-11 07:57:30.062 +00:00 INFO config/load.go:48 query secret workers: 4
2019-03-11 07:57:30.062 +00:00 INFO config/messagelayer.go:18 message layer: context
2019-03-11 07:57:30.066 +00:00 INFO core/module.go:54 module controller registered
2019-03-11 07:57:30.066 +00:00 INFO core/core.go:23 starting module cloudhub
2019-03-11 07:57:30.066 +00:00 INFO core/core.go:23 starting module controller
panic: open tmp/test.crt: no such file or directory

goroutine 12 [running]:
github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/cloudhub.(*cloudHub).Start(0xc000010110, 0xc0002317c0)
	/usr/local/go/src/github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/cloudhub/cloudhub.go:46 +0x518
created by github.com/kubeedge/kubeedge/common/beehive/pkg/core.StartModules
	/usr/local/go/src/github.com/kubeedge/kubeedge/common/beehive/pkg/core/core.go:22 +0x166
```
 + Create a `tmp` directory and create `tmp/test.crt`
```
$ openssl genrsa -des3 -out test.key 4096
$ openssl req -x509 -new -nodes -key test.key -sha256 -days 1024 -out test.crt
```
+ Execute `./edgecontroller` error
```
./edgecontroller
2019/03/11 08:03:05 WARN: empty configurtion from [CommandlineSource]
2019/03/11 08:03:05 WARN: empty configurtion from [MemorySource]
New file source added for configuration: /home/ubuntu/go/src/github.com/kubeedge/kubeedge/cloud/edgecontroller/conf/controller.yamlNew file source added for configuration: /home/ubuntu/go/src/github.com/kubeedge/kubeedge/cloud/edgecontroller/conf/logging.yamlNew file source added for configuration: /home/ubuntu/go/src/github.com/kubeedge/kubeedge/cloud/edgecontroller/conf/modules.yaml/home/ubuntu/go/src/github.com/kubeedge/kubeedge/cloud/edgecontroller/conf/logging.yamllogConfig:&{INFO edgecontroller.log [file stdout] true false  }
2019/03/11 08:03:05 RollingPolicy is empty, use default policy[size]
2019-03-11 08:03:05.584 +00:00 INFO core/module.go:54 module cloudhub registered
2019-03-11 08:03:05.586 +00:00 INFO config/buffer.go:27 update pod status buffer: 1024
2019-03-11 08:03:05.586 +00:00 INFO config/buffer.go:34 Update node status buffer: 1024
2019-03-11 08:03:05.586 +00:00 INFO config/buffer.go:41 query config map buffer: 1024
2019-03-11 08:03:05.586 +00:00 INFO config/buffer.go:48 query secret buffer: 1024
2019-03-11 08:03:05.586 +00:00 INFO config/context.go:28  send module name: cloudhub
2019-03-11 08:03:05.586 +00:00 INFO config/context.go:35 receive module name: controller
2019-03-11 08:03:05.586 +00:00 INFO config/context.go:42 response module name: cloudhub
2019-03-11 08:03:05.586 +00:00 INFO config/kube.go:38 kube master: http://localhost:8080
2019-03-11 08:03:05.586 +00:00 ERROR config/kube.go:41 kube config not set
2019-03-11 08:03:05.586 +00:00 INFO config/kube.go:45 kube config:
2019-03-11 08:03:05.586 +00:00 INFO config/kube.go:52 kube namespace:
2019-03-11 08:03:05.586 +00:00 INFO config/kube.go:59 kube content type: application/vnd.kubernetes.protobuf
2019-03-11 08:03:05.586 +00:00 INFO config/kube.go:66 kube QPS: 5.000000
2019-03-11 08:03:05.586 +00:00 INFO config/kube.go:73 kube burst: 10
2019-03-11 08:03:05.586 +00:00 INFO config/kube.go:80 kube update frequency: 10s
2019-03-11 08:03:05.586 +00:00 INFO config/load.go:27 update pod status workers: 1
2019-03-11 08:03:05.586 +00:00 INFO config/load.go:34 update node status workers: 1
2019-03-11 08:03:05.586 +00:00 INFO config/load.go:41 query config map workers: 4
2019-03-11 08:03:05.586 +00:00 INFO config/load.go:48 query secret workers: 4
2019-03-11 08:03:05.586 +00:00 INFO config/messagelayer.go:18 message layer: context
2019-03-11 08:03:05.591 +00:00 INFO core/module.go:54 module controller registered
2019-03-11 08:03:05.591 +00:00 INFO core/core.go:23 starting module cloudhub
2019-03-11 08:03:05.591 +00:00 INFO core/core.go:23 starting module controller
2019-03-11 08:03:05.591 +00:00 INFO controller/upstream.go:95 start upstream controller
panic: tls: failed to parse private key

goroutine 26 [running]:
github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/cloudhub/wsserver.StartCloudHub(0xc000100500, 0xc00043a2a0)
	/usr/local/go/src/github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/cloudhub/wsserver/server.go:384 +0x88a
github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/cloudhub.(*cloudHub).Start(0xc0000c2100, 0xc00023d780)
	/usr/local/go/src/github.com/kubeedge/kubeedge/cloud/edgecontroller/pkg/cloudhub/cloudhub.go:62 +0x32e
created by github.com/kubeedge/kubeedge/common/beehive/pkg/core.StartModules
	/usr/local/go/src/github.com/kubeedge/kubeedge/common/beehive/pkg/core/core.go:22 +0x166
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version: master branch
- Hardware configuration: 4 core 16G
- OS (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS
- Kernel (e.g. `uname -a`): Linux i-i088o33c 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Others: AWS EC2

**Comment by edisonxiang** [comment] 2019-03-12 01:33
@zhanghongtong Hey, could you generate the cert/key pair by the way?
https://github.com/kubeedge/kubeedge#generate-certificates

The `tmp/rootCA.crt` is also required, Thanks
https://github.com/kubeedge/kubeedge/blob/master/cloud/edgecontroller/conf/controller.yaml#L12-L14

**Comment by zhanghongtong** [comment] 2019-03-12 01:54
@edisonxiang Yes, I put all the cert/key pairs in the tmp directory, and `./edgecontroller` will still report `panic: tls: failed to parse private key`
```
$ ll $GOPATH/src/github.com/kubeedge/kubeedge/cloud/edgecontroller/tmp
total 40
drwxrwxr-x 2 ubuntu ubuntu 4096 Mar 11 08:04 ./
drwxrwxr-x 6 ubuntu ubuntu 4096 Mar 11 08:09 ../
-rw-r--r-- 1 root   root   1456 Mar 11 07:57 kubeedge.crt
-rw-r--r-- 1 root   root    956 Mar 11 07:57 kubeedge.csr
-rw------- 1 root   root   1675 Mar 11 07:57 kubeedge.key
-rw-r--r-- 1 root   root   1923 Mar 11 07:57 rootCA.crt
-rw------- 1 root   root   3311 Mar 11 07:57 rootCA.key
-rw-r--r-- 1 root   root     17 Mar 11 07:57 rootCA.srl
-rw-rw-r-- 1 ubuntu ubuntu    0 Mar 11 08:04 test.crt
-rw-rw-r-- 1 ubuntu ubuntu  956 Mar 11 08:04 test.csr
-rw------- 1 ubuntu ubuntu 1675 Mar 11 08:03 test.key
```

**Comment by edisonxiang** [comment] 2019-03-12 01:56
@zhanghongtong It seems like the test.crt file size is 0
You can delete test.* and rename kubedge.* into test.*

**Comment by zhanghongtong** [comment] 2019-03-12 01:57
@edisonxiang Thank you, let me try

**Comment by sids-b** [comment] 2019-03-12 01:57
@zhanghongtong ,in these steps ( https://github.com/kubeedge/kubeedge/#generate-certificates ) we generate rootCA.crt , kubeedge.crt and kubeedge.key . You need to have something like this in configurations of edgecontroller (controller.yaml) 
``` 
ca: <path-of-directory-of-generated-certificates>/rootCA.crt
cert: <path-of-directory-of-generated-certificates>/kubeedge.crt
key: <path-of-directory-of-generated-certificates>/kubeedge.key
```
And in edge_core configurations(edge.yaml)
```
certfile: <path-of-directory-of-generated-certificates>/kubeedge.crt
keyfile: <path-of-directory-of-generated-certificates>/kubeedge.key
```

**Comment by sids-b** [comment] 2019-03-13 03:43
@zhanghongtong , I am closing this issue. Please feel free to ping us on slack if you are still facing any problem.

**Comment by zhanghongtong** [comment] 2019-03-16 15:39
@sids-b @edisonxiang Thanks

**Comment by m1093782566** [comment] 2019-03-18 08:19
@zhanghongtong 

Seems the issue is resolved. I am going to close this issue. Please feel free to re-open if you still have the same trouble.

**Closed by m1093782566** 2019-03-18 08:19 UTC
Labels: kind/bug
