### ISSUE TITLE
Move Docs to website repository and proposals to enhancements repository.

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#288] opened 2019-03-22 11:30 UTC
**What would you like to be added**:
Move docs to website repository and proposals to enhancement repository.

**Why is this needed**:
The hyperlinks in the docs have a .html link which results does not redirect to correct page while moving browsing the docs in github repository.
Also moving proposals to enhancements and docs to website repository will help in seperation and easy management/review of source code, documentation and enhancement proposals.

Thoughts ??
@kevin-wangzefeng @rohitsardesai83 @m1093782566 @CindyXing @qizha

**Comment by m1093782566** [comment] 2019-03-22 11:34
I think docs should be in website repo and the new enhancements repo only for proposals.

**Comment by rohitsardesai83** [comment] 2019-03-22 11:34
:+1:

**Comment by sids-b** [comment] 2019-03-22 11:36
> I think docs should be in website repo and the new enhancements repo only for proposals.

+1

**Comment by anvithks** [comment] 2019-03-24 08:40
Moving the docs to the website repository will open up two possibilities.  
1. Documentation can be displayed on the website itself.  
2. Documentation can be displayed as it is currently being done, using readthedocs.  

If we go with option 1 then developers will have to follow the markdown and shortcodes that are required for the website.   
If we go with option 2 they can continue doing what they are doing but need to make sure they follow the contribution guides and style guides for readthedocs.  
Either way, if we continue using the Readme files to have all the information we need to make sure we update the relevant sections in the documentation pages.   
There are some parts which are duplicated. We have to decide which parts can be removed from the Readme files.  
There will be some overhead on developers to make sure documentation is done properly.  
With the current process we will end up having to make a lot of fixes after merging new PR'S.  
I recommend having two reviewers for documentation PR's. One technical writer/developer who can verify the contents and one person who can verify the document style guides and contribution guides are being followed.

**Comment by anvithks** [comment] 2019-03-24 09:18
@sids-b the issue reported above regarding html files and location of files cannot be solved since we are using readthedocs to generate the docs. The path will be different from the source doc.
For this we will have to keep the docs in another repo instead of the website repo.

**Comment by sids-b** [comment] 2019-03-24 12:03
> @sids-b the issue reported above regarding html files and location of files cannot be solved since we are using readthedocs to generate the docs. The path will be different from the source doc.
> For this we will have to keep the docs in another repo instead of the website repo.

@anvithks What would you suggest as a solution ? We need to enable github browsing of documents as well.

**Comment by anvithks** [comment] 2019-03-25 04:04
Anyone can browse the docs on github now. But if you try to create a navigation within the github repo for documentation then you are going to have two different places for people to access docs. This may lead to confusion which is not desirable .  
I recommend having it in one place, which is readthedocs at the moment.  
Do remember that moving the docs to another repository will mean that developers will have to maintain and contribute to  two repositories.  This will definitely increase the maintenance overhead as the content increases and we add more and more features.  
If a better solution is available I would like to hear about it and explore the same.

**Comment by sids-b** [comment] 2019-03-25 04:45
@anvithks If the content and number of features increases, it will be better if we have different repositories as maintenance would for docs and source code can be done independently right ? Also I feel contributing to 2 repositories will not be a problem.

Also navigation on github has to enabled. Many users like to browse the docs on github......

**Comment by anvithks** [comment] 2019-03-25 10:29
@sids-b 
> @anvithks If the content and number of features increases, it will be better if we have different repositories as maintenance for docs and source code can be done independently right ? 
>
Can this be done? Yes.  
Is it going to add overhead on developers? Yes.  
> Also I feel contributing to 2 repositories will not be a problem.
> 
I disagree.  The lesser repositories I have to deal with the better. That's just my opinion though. I am pretty sure there are many who would be OK to have multiple repositories.  

> Also navigation on github has to enabled. Many users like to browse the docs on github......
>
Again I disagree.  
If you are going to have a website / docs site then giving another avenue to access the same with a different navigation will definitely lead to confusion.  
I reiterate, our docs are being generated with readthedocs (RTD). One of the steps in this is generating the Table Of Contents (TOC) . This TOC can be configured by us and we can have create different sections on the site.  
For ex: The `General Concepts`, `Edge Concepts` and `Cloud Concepts` sections in the menu are all generated from the TOC configuration. In the docs folder they are all under `docs/modules` folder.  

The navigation and even the display can be changed and optimized without having to change the file locations.  
If we have to do the same with providing a navigation on Github you will definitely end up duplicating effort.  
Whenever we make changes or add to the doc we will have to update the RTD as well the GitHub navigation.

**Comment by sids-b** [comment] 2019-04-08 13:00
Can we move the docs folder as it is to the website repo ( Let us not change the readthedocs way of generating documentation ). This will not increase complexity of understanding grammar and will also keep docs related to kubeedge understanding/modules as well as other docs (like proposals, performance test docs, etc) different so that maintainability is also easy. 

I feel for a developer cloning 2 repo's and adding commits in 2 different repos will not be a big overhead.

**Comment by yongwww** [comment] 2019-04-14 02:06
+1

**Comment by skdwriting** [comment] 2019-04-14 02:27
Why don't we have a separate repo for documentation? Then organize all docs accordingly.
a) docs on website can still use readthedoc model
b) website pages, let us know mix with documentation of the project. It could be duplicate data of all these docs. The page content can be organized within website.
c) documentation repo can have a readme file about a simple diagram explaining the overall docs organizations and guide to doc / webpage developers.
This could be well organized and scalable.
Another view!

**Comment by m1093782566** [comment] 2019-04-14 02:29
@skdwriting 

Can we use the website repo for all the documentations?

**Comment by skdwriting** [comment] 2019-04-14 02:42
@m1093782566 , this is what many other projects do. However, I feel, it is better we keep documentation under documentation repo. It is cleaner and scalable. Let the website repo deals only the website related code/contents. 
Unless someone has a big technical issue on this, i recommend this!
Once we do it in a cleaner way, others can follow! :)
However if there is big technical issue, we can check/review for sure...

Another ref : #274

**Comment by m1093782566** [comment] 2019-04-14 02:45
@skdwriting @anvithks 

I want to know the technical issues on putting all the documentations to the website repo.

>  It is cleaner and scalable. Let the website repo deals only the website related code/contents.

I think we can use different folder to organize the contents of docs and website.

**Comment by anvithks** [comment] 2019-04-17 04:50
If you want to move the docs out then move it to another repository and not under the website repository.
This will be better in terms of having completely independent management and not having to worry about some conflicts with the website generation.

**Comment by kevin-wangzefeng** [comment] 2019-04-17 11:48
Removed "good first issue" label.

**Comment by kevin-wangzefeng** [comment] 2019-04-20 08:07
> The hyperlinks in the docs have a .html link which results does not redirect to correct page while moving browsing the docs in github repository.

This is actually a bug, when browing through readthedocs, the link is .html, while when browsing in the github repository it needs .md link. 

Per prior discussion, to get best document contributor-experience, we need to help writers just focus on the content (only aware of .md files not .html things)
Besides, regarding the current docs location, people who cloned the repo may read docs directly in files. So it's recommended to use .md links to indicate the real file location in content. 

In this case, we need to figure out how to turn the links into .html suffix automatically when deployed to document website. We may probably move out of readthedocs if it doesn't support this. (And we also have other document looking issue not yet solved.)
Or, just move docs out of the main repo and provide only browsing through docs.kubeedge.io. Please note that the contributor experience is not improved in this case. It's just a easy way to get things fixed.

> Also moving proposals to enhancements and docs to website repository will help in seperation and easy management/review of source code, documentation and enhancement proposals.

We may have an individual repo to maintain proposals as well as other community governance docs in the longer term. Proposals don't need to go with docs.

**Comment by anvithks** [comment] 2019-04-22 03:57
@kevin-wangzefeng This is not a bug. This is how readthedocs works. It generates html pages from our md files. The link to the md files is available in the "Edit this document is Github" link at the top right corner.
The user does not have to create html files. Readthedocs does that for you.
Our website is using the hugo generator that does pretty much the same thing. But it has a few more shortcodes and front matter  that helps in formatting the pages. 
Even if we move the docs to another repo or the website repo, we will have to use either readthedocs or some other method to convert the docs to a website. In this case as well if a user ends up in the repository they will see the md files directly. We cannot have the same navigation as readthedocs since we use the TOC generator on readthedocs and in github we will have to create manual links.
I have listed out some issues in the comments above.
Proposals are currently excluded from the generated website. They do not show up in the documentation site at docs.kubeedge.io
Please let me know if you need more information on this.

**Comment by skdwriting** [comment] 2019-04-22 05:43
@anvithks , when readthedocs build the docs from github, is there a separate copy for each document created and maintained by readthedocs for the website?

**Comment by anvithks** [comment] 2019-04-22 05:59
@skdwriting Readthedocs uses generators that build html files(in case we use html folder generator) or a single html file (in case we use a singleHtml generator) from the md files in our docs folders.
This is being done on their site (kubeedge.readthedocs.io). Whenever a PR is merged into the docs/ folder (except for the exclude folder list) in our kubeedge repository the build script is fired and a new version is generated.
If we want to edit the files, readthedocs provides a link on every page at the top which says "Edit on Github". This opens the doc in the Github markdown editor.

**Comment by rohitsardesai83** [comment] 2019-05-02 10:46
any conclusion on this ? I filed #442 as I came across this issue , I am not sure community users might also be facing issues ? we need to close soon.

**Comment by sids-b** [comment] 2019-05-04 05:45
agree with @rohitsardesai83 , lets close this one before minor release

**Comment by edisonxiang** [comment] 2019-05-08 07:13
I am facing this problem now as #470 discussed.

> Move Docs to website repository and proposals to enhancements repository

+1 we should separate these two kinds of documents since we are using md in github repository but html in website.

**Comment by kevin-wangzefeng** [comment] 2019-05-08 14:50
Probably put a full `.md` file link next to html link by now?

**Comment by anvithks** [comment] 2019-05-08 16:22
> I am facing this problem now as #470 discussed.
> 
> > Move Docs to website repository and proposals to enhancements repository
> 
> +1 we should separate these two kinds of documents since we are using md in github repository but html in website.

I think there is still confusion as to how the documentation is generated.

1. We use readthedocs to generate our documentation website at docs.kubeedge.io (redirected from kubeedge.readthedocs.io).
2. readthedocs uses the files from the /docs folder in the kubeedge/kubeedge repository and the SphinxHtmlDir generator to generate the website html files.
3. This generated html is then served as a website with all the styling and the navigation.
4. To edit the file at anytime there is a "Edit this File on GitHub" link provided at the top of the page.


> any conclusion on this ? I filed #442 as I came across this issue , I am not sure community users might also be facing issues ? we need to close soon.

Coming to this issue, I have gone through the readthedocs forums and can say that this is a common issue faced when a build is in progress OR a PR which is breaking the build.
How this can be avoided is to make sure that PRs are thoroughly reviewed to be readthedocs compliant before merging them.

**Please Note:** 
1. No documentation generator provides a website like behaviour (with navigation and out of the box mobile support). (If there are any, please let me know and I will explore the option.)
2. I think the issue of the extension of the file is trivial. As long as you make it clear how anyone can contribute to the docs. (Users just have to edit the appropriate file, by clicking the "Edit on GitHub" button or by editing the source file.)

**Comment by yamt** [comment] 2019-06-14 02:13
IMO, the majority of doc should stay within the repo because it helps to keep code and doc in sync.

the md/html mismatch issue can be fixed programmatically. Like https://github.com/kubeedge/kubeedge/pull/704/commits/13da7623373c310d52811c2f62f95222080cff25

**Comment by anvithks** [comment] 2019-06-16 11:45
@yamt the AutoStructify option seems to be something that can help. 
Thanks.

**Closed** 2019-07-02 12:31 UTC
Labels: help wanted, important-soon, kind/bug, kind/cleanup, kind/documentation
