### ISSUE TITLE
edge node join fialed with version v1.13.0

### ISSUE THREAD

**Issue by charnet1019** [kubeedge/kubeedge#4589] opened 2023-02-08 07:54 UTC
**What happened and what you expected to happen**:
```
[root@node2 ~]# keadm join --cloudcore-ipport=10.0.0.56:10000 --edgenode-name edgenode-test --kubeedge-version v1.13.0 --runtimetype remote --remote-runtime-endpoint unix:///run/containerd/containerd.sock --token=c58ddaa974a8c04a34abcdeef96333a4fd0bf79555e113403b5de9201c1242db.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzU5Mjc5Njh9.4wx37o7MsNrjBA85KVyGG1oGIN7m4N4nMcU6XOZ_6oI
I0208 15:45:05.075962  193655 command.go:845] 1. Check KubeEdge edgecore process status
I0208 15:45:05.080283  193655 command.go:845] 2. Check if the management directory is clean
I0208 15:45:05.080352  193655 join.go:107] 3. Create the necessary directories
I0208 15:45:05.082906  193655 join.go:184] 4. Pull Images
Pulling kubeedge/installation-package:v1.13.0 ...
Successfully pulled kubeedge/installation-package:v1.13.0
Pulling eclipse-mosquitto:1.6.15 ...
Successfully pulled eclipse-mosquitto:1.6.15
Pulling kubeedge/pause:3.6 ...
Successfully pulled kubeedge/pause:3.6
I0208 15:45:05.084095  193655 join.go:184] 5. Copy resources from the image to the management directory
E0208 15:45:25.084405  193655 remote_runtime.go:198] "RunPodSandbox from runtime service failed" err="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
Error: edge node join failed: copy resources failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
execute keadm command failed:  edge node join failed: copy resources failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**system logs:**
![image](https://user-images.githubusercontent.com/18616254/217480117-ac6bd541-952d-4097-8743-a2e7c2fa80f1.png)

After labeling docker.io/kubedge/pause: 3.6 as registry.k8s.io/pause: 3.6, the following error is reported:
```
[root@node2 ~]# keadm join --cloudcore-ipport=10.0.0.56:10000 --edgenode-name edgenode-test --kubeedge-version v1.13.0 --runtimetype remote --remote-runtime-endpoint unix:///run/containerd/containerd.sock --token=c58ddaa974a8c04a34abcdeef96333a4fd0bf79555e113403b5de9201c1242db.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzU5Mjc5Njh9.4wx37o7MsNrjBA85KVyGG1oGIN7m4N4nMcU6XOZ_6oI
I0208 17:28:08.688859  146506 command.go:845] 1. Check KubeEdge edgecore process status
I0208 17:28:08.693334  146506 command.go:845] 2. Check if the management directory is clean
I0208 17:28:08.693393  146506 join.go:107] 3. Create the necessary directories
I0208 17:28:08.697407  146506 join.go:184] 4. Pull Images
Pulling eclipse-mosquitto:1.6.15 ...
Successfully pulled eclipse-mosquitto:1.6.15
Pulling kubeedge/pause:3.6 ...
Successfully pulled kubeedge/pause:3.6
Pulling kubeedge/installation-package:v1.13.0 ...
Successfully pulled kubeedge/installation-package:v1.13.0
I0208 17:28:08.698871  146506 join.go:184] 5. Copy resources from the image to the management directory
E0208 17:28:08.699778  146506 remote_runtime.go:198] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to reserve sandbox name \"edgecore_kubeedge__0\": name \"edgecore_kubeedge__0\" is reserved for \"aaef38a05b3819112390bd8c16b95a0c88014f693b89053275366e583853a794\""
Error: edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to reserve sandbox name "edgecore_kubeedge__0": name "edgecore_kubeedge__0" is reserved for"aaef38a05b3819112390bd8c16b95a0c88014f693b89053275366e583853a794"
execute keadm command failed:  edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to reserve sandbox name "edgecore_kubeedge__0": name "edgecore_kubeedge__0" is reserved for "aaef38a05b3819112390bd8c16b95a0c88014f693b89053275366e583853a794"
```

**How to reproduce it (as minimally and precisely as possible)**:
setup cloudcore:
```
keadm init --advertise-address=10.0.0.56 --profile version=v1.13.0 --kube-config=/root/.kube/config
```
setup edgecore:
```
keadm join --cloudcore-ipport=10.0.0.56:10000 --edgenode-name edgenode-test --kubeedge-version v1.13.0 --runtimetype remote --remote-runtime-endpoint unix:///run/containerd/containerd.sock --token=c58ddaa974a8c04a34abcdeef96333a4fd0bf79555e113403b5de9201c1242db.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzU5Mjc5Njh9.4wx37o7MsNrjBA85KVyGG1oGIN7m4N4nMcU6XOZ_6oI
```

Use kubeedge v1.21.1 can setup, but reported the following errors:
```
Feb  9 10:34:58 node2 edgecore: E0209 10:34:58.733720  131971 pod_workers.go:915] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"upgrade-ipam\" with ImagePullBackOff: \"Back-off pulling image \\\"172.31.0.5:5000/cni:v3.17.1\\\"\"" pod="kube-system/calico-node-l965z" podUID=37a1b469-b7be-44fd-9588-4937076429c8
Feb  9 10:35:01 node2 edgecore: E0209 10:35:01.391176  131971 pod_workers.go:915] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"upgrade-ipam\" with ImagePullBackOff: \"Back-off pulling image \\\"172.31.0.5:5000/cni:v3.17.1\\\"\"" pod="kube-system/calico-node-l965z" podUID=37a1b469-b7be-44fd-9588-4937076429c8
Feb  9 10:35:05 node2 edgecore: E0209 10:35:05.733815  131971 pod_workers.go:915] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-proxy\" with ImagePullBackOff: \"Back-off pulling image \\\"172.31.0.5:5000/kube-proxy:v1.20.2\\\"\"" pod="kube-system/kube-proxy-t4bb2" podUID=07f4fa03-c7f5-4ddb-a74e-ca386c1af867
Feb  9 10:35:06 node2 edgecore: E0209 10:35:06.698280  131971 pod_workers.go:915] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"upgrade-ipam\" with ImagePullBackOff: \"Back-off pulling image \\\"172.31.0.5:5000/cni:v3.17.1\\\"\"" pod="kube-system/calico-node-l965z" podUID=37a1b469-b7be-44fd-9588-4937076429c8
Feb  9 10:35:06 node2 edgecore: E0209 10:35:06.750282  131971 pod_workers.go:915] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-proxy\" with ImagePullBackOff: \"Back-off pulling image \\\"172.31.0.5:5000/kube-proxy:v1.20.2\\\"\"" pod="kube-system/kube-proxy-t4bb2" podUID=07f4fa03-c7f5-4ddb-a74e-ca386c1af867
Feb  9 10:35:11 node2 edgecore: E0209 10:35:11.197759  131971 pod_workers.go:915] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-proxy\" with ImagePullBackOff: \"Back-off pulling image \\\"172.31.0.5:5000/kube-proxy:v1.20.2\\\"\"" pod="kube-system/kube-proxy-t4bb2" podUID=07f4fa03-c7f5-4ddb-a74e-ca386c1af867
Feb  9 10:35:20 node2 edgecore: E0209 10:35:20.731785  131971 pod_workers.go:915] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"upgrade-ipam\" with ImagePullBackOff: \"Back-off pulling image \\\"172.31.0.5:5000/cni:v3.17.1\\\"\"" pod="kube-system/calico-node-l965z" podUID=37a1b469-b7be-44fd-9588-4937076429c8
Feb  9 10:35:25 node2 edgecore: E0209 10:35:25.746949  131971 pod_workers.go:915] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-proxy\" with ImagePullBackOff: \"Back-off pulling image \\\"172.31.0.5:5000/kube-proxy:v1.20.2\\\"\"" pod="kube-system/kube-proxy-t4bb2" podUID=07f4fa03-c7f5-4ddb-a74e-ca386c1af867
Feb  9 10:35:32 node2 edgecore: E0209 10:35:32.731957  131971 pod_workers.go:915] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"upgrade-ipam\" with ImagePullBackOff: \"Back-off pulling image \\\"172.31.0.5:5000/cni:v3.17.1\\\"\"" pod="kube-system/calico-node-l965z" podUID=37a1b469-b7be-44fd-9588-4937076429c8
Feb  9 10:35:39 node2 edgecore: E0209 10:35:39.733455  131971 pod_workers.go:915] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-proxy\" with ImagePullBackOff: \"Back-off pulling image \\\"172.31.0.5:5000/kube-proxy:v1.20.2\\\"\"" pod="kube-system/kube-proxy-t4bb2" podUID=07f4fa03-c7f5-4ddb-a74e-ca386c1af867
Feb  9 10:35:46 node2 edgecore: E0209 10:35:46.730988  131971 pod_workers.go:915] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"upgrade-ipam\" with ImagePullBackOff: \"Back-off pulling image \\\"172.31.0.5:5000/cni:v3.17.1\\\"\"" pod="kube-system/calico-node-l965z" podUID=37a1b469-b7be-44fd-9588-4937076429c8
Feb  9 10:35:53 node2 edgecore: E0209 10:35:53.734155  131971 pod_workers.go:915] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-proxy\" with ImagePullBackOff: \"Back-off pulling image \\\"172.31.0.5:5000/kube-proxy:v1.20.2\\\"\"" pod="kube-system/kube-proxy-t4bb2" podUID=07f4fa03-c7f5-4ddb-a74e-ca386c1af867
Feb  9 10:35:58 node2 edgecore: E0209 10:35:58.733109  131971 pod_workers.go:915] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"upgrade-ipam\" with ImagePullBackOff: \"Back-off pulling image \\\"172.31.0.5:5000/cni:v3.17.1\\\"\"" pod="kube-system/calico-node-l965z" podUID=37a1b469-b7be-44fd-9588-4937076429c8
```

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): v1.20.2
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): cloudcore v1.13.0  edgecore:v1.13.0
- Containerd version: 1.6.16

**Comment by RyanZhaoXB** [comment] 2023-02-10 07:11
it seems that containerd didn't work properly. see this issue: https://github.com/containerd/cri/issues/1014#issuecomment-873623168

**Comment by truepele** [comment] 2023-02-13 08:27
Does anyone have any ideas for a workaround?

**Comment by truepele** [comment] 2023-02-13 22:52
I get the error right away when running a `join`. Any suggestions/directions for troubleshooting?

```
keadm join --cloudcore-ipport="<...>":10000 --kubeedge-version=v1.13.0 --token="..."
I0213 22:48:56.007803    5161 command.go:845] 1. Check KubeEdge edgecore process status
I0213 22:48:56.014033    5161 command.go:845] 2. Check if the management directory is clean
I0213 22:48:56.014219    5161 join.go:107] 3. Create the necessary directories
I0213 22:48:56.017156    5161 join.go:184] 4. Pull Images
Pulling kubeedge/installation-package:v1.13.0 ...
Successfully pulled kubeedge/installation-package:v1.13.0
Pulling eclipse-mosquitto:1.6.15 ...
Successfully pulled eclipse-mosquitto:1.6.15
Pulling kubeedge/pause:3.6 ...
Successfully pulled kubeedge/pause:3.6
I0213 22:48:56.018764    5161 join.go:184] 5. Copy resources from the image to the management directory
E0213 22:48:56.020031    5161 remote_runtime.go:198] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to reserve sandbox name \"edgecore_kubeedge__0\": name \"edgecore_kubeedge__0\" is reserved for \"ca2923500ae1de9b7d55cfe10836585a1ce56adf13e94800d8f991c035cab6ac\""
Error: edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to reserve sandbox name "edgecore_kubeedge__0": name "edgecore_kubeedge__0" is reserved for "ca2923500ae1de9b7d55cfe10836585a1ce56adf13e94800d8f991c035cab6ac"
execute keadm command failed:  edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to reserve sandbox name "edgecore_kubeedge__0": name "edgecore_kubeedge__0" is reserved for "ca2923500ae1de9b7d55cfe10836585a1ce56adf13e94800d8f991c035cab6ac"
```

**Comment by Marovlo** [comment] 2023-02-20 05:04
I get the same when running a **join** 

> I get the error right away when running a `join`. Any suggestions/directions for troubleshooting?
> 
> ```
> keadm join --cloudcore-ipport="<...>":10000 --kubeedge-version=v1.13.0 --token="..."
> I0213 22:48:56.007803    5161 command.go:845] 1. Check KubeEdge edgecore process status
> I0213 22:48:56.014033    5161 command.go:845] 2. Check if the management directory is clean
> I0213 22:48:56.014219    5161 join.go:107] 3. Create the necessary directories
> I0213 22:48:56.017156    5161 join.go:184] 4. Pull Images
> Pulling kubeedge/installation-package:v1.13.0 ...
> Successfully pulled kubeedge/installation-package:v1.13.0
> Pulling eclipse-mosquitto:1.6.15 ...
> Successfully pulled eclipse-mosquitto:1.6.15
> Pulling kubeedge/pause:3.6 ...
> Successfully pulled kubeedge/pause:3.6
> I0213 22:48:56.018764    5161 join.go:184] 5. Copy resources from the image to the management directory
> E0213 22:48:56.020031    5161 remote_runtime.go:198] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to reserve sandbox name \"edgecore_kubeedge__0\": name \"edgecore_kubeedge__0\" is reserved for \"ca2923500ae1de9b7d55cfe10836585a1ce56adf13e94800d8f991c035cab6ac\""
> Error: edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to reserve sandbox name "edgecore_kubeedge__0": name "edgecore_kubeedge__0" is reserved for "ca2923500ae1de9b7d55cfe10836585a1ce56adf13e94800d8f991c035cab6ac"
> execute keadm command failed:  edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to reserve sandbox name "edgecore_kubeedge__0": name "edgecore_kubeedge__0" is reserved for "ca2923500ae1de9b7d55cfe10836585a1ce56adf13e94800d8f991c035cab6ac"
> ```

**Comment by Piwriw** [comment] 2023-02-22 01:25
I suggest you use Public network ip ( --cloudcore-ipport=) and try again

**Comment by Piwriw** [comment] 2023-02-22 01:26
Maybe you should try use publish network ip(--cloudcore-ipport)

**Comment by truepele** [comment] 2023-03-11 06:05
> Maybe you should try use publish network ip(--cloudcore-ipport)

@Piwriw can you please elaborate a bit more?
I did use a public ip for the `cloudcore-ipport` parameter.
The error does not seem to be related to connectivity between nodes:
```
failed to reserve sandbox name "edgecore_kubeedge__0": name "edgecore_kubeedge__0" is reserved for "ca2923500ae1de9b7d55cfe10836585a1ce56adf13e94800d8f991c035cab6ac
```

**Comment by Piwriw** [comment] 2023-03-11 07:47
> 

You use `_` with your edge name? In my impression, it will be wrong.

**Comment by Piwriw** [comment] 2023-03-11 07:48
> > Maybe you should try use publish network ip(--cloudcore-ipport)
> 
> @Piwriw can you please elaborate a bit more? I did use a public ip for the `cloudcore-ipport` parameter. The error does not seem to be related to connectivity between nodes:
> 
> ```
> failed to reserve sandbox name "edgecore_kubeedge__0": name "edgecore_kubeedge__0" is reserved for "ca2923500ae1de9b7d55cfe10836585a1ce56adf13e94800d8f991c035cab6ac
> ```

You use `_` with your edge name? In my impression, it will be wrong.

**Comment by wuxs** [comment] 2023-04-14 06:56
我也碰到相同的问题了，是cni插件配置的问题
安装 containerd v1.16.12 + cni v1.1.1
使用下面的命令创建cni配置，重新安装edgecore就可以了
```
cat > /etc/cni/net.d/10-containerd-net.conflist <<EOF
{
     "cniVersion": "1.0.0",
     "name": "containerd-net",
     "plugins": [
       {
         "type": "bridge",
         "bridge": "cni0",
         "isGateway": true,
         "ipMasq": true,
         "promiscMode": true,
         "ipam": {
           "type": "host-local",
           "ranges": [
             [{
               "subnet": "10.88.0.0/16"
             }],
             [{
               "subnet": "2001:db8:4860::/64"
             }]
           ],
           "routes": [
             { "dst": "0.0.0.0/0" },
             { "dst": "::/0" }
           ]
         }
       },
       {
         "type": "portmap",
         "capabilities": {"portMappings": true}
       }
     ]
    }
EOF
```

**Comment by JiaweiGithub** [comment] 2023-04-19 09:13
> 我也碰到相同的问题了，是cni插件配置的问题 安装 containerd v1.6.20 + cni v1.1.1 使用下面的命令创建cni配置，重新安装edgecore就可以了
> 
> ```
> cat > /etc/cni/net.d/10-containerd-net.conflist <<EOF
> {
>      "cniVersion": "1.0.0",
>      "name": "containerd-net",
>      "plugins": [
>        {
>          "type": "bridge",
>          "bridge": "cni0",
>          "isGateway": true,
>          "ipMasq": true,
>          "promiscMode": true,
>          "ipam": {
>            "type": "host-local",
>            "ranges": [
>              [{
>                "subnet": "10.88.0.0/16"
>              }],
>              [{
>                "subnet": "2001:db8:4860::/64"
>              }]
>            ],
>            "routes": [
>              { "dst": "0.0.0.0/0" },
>              { "dst": "::/0" }
>            ]
>          }
>        },
>        {
>          "type": "portmap",
>          "capabilities": {"portMappings": true}
>        }
>      ]
>     }
> EOF
> ```

What is your Kubernetes version? I'm getting this error and my Kubernetes version is 1.22.

**Comment by univwang** [comment] 2023-05-19 08:31
my error message: failed to reserve sandbox name "edgecore___0":

**Comment by luomengY** [comment] 2023-05-26 15:02
我也遇到了相同的问题，请问怎么解决的？
execute keadm command failed:  edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to reserve sandbox name "edgecore_kubeedge__0": name "edgecore_kubeedge__0" is reserved for "42bde66aa0bdb259a8244ea7b3695642e6615825c70cfe69e567fd9528565768"

**Comment by yjqg6666** [comment] 2023-05-31 06:03
Resolved by reading the code and add an option ` --runtimetype=docker`

[join request](https://github.com/kubeedge/kubeedge/blob/v1.13.0/keadm/cmd/keadm/app/cmd/edge/image.go#L33-L49) and [join options](https://github.com/kubeedge/kubeedge/blob/v1.13.0/keadm/cmd/keadm/app/cmd/edge/join.go#L120-L162)
`
cmd.Flags().StringVarP(&joinOptions.RuntimeType, common.RuntimeType, "r", joinOptions.RuntimeType,
		"Container runtime type")
	cmd.Flags().StringVarP(&joinOptions.RemoteRuntimeEndpoint, common.RemoteRuntimeEndpoint, "p", joinOptions.RemoteRuntimeEndpoint,
		"KubeEdge Edge Node RemoteRuntimeEndpoint string, If flag not set, it will use unix:///run/containerd/containerd.sock")
`
It failed, may be caused by not-running containerd or docker.

Here reserve sandbox name 'edgecore_kubeedge_0' which might mean the container exist, try container runtime tool to remove container.

**Comment by yjqg6666** [comment] 2023-07-14 04:25
For containerd:
  1. check ps:
`$ nerdctl ps -a --namespace k8s.io`
> CONTAINER ID    IMAGE                           COMMAND     CREATED              STATUS     PORTS    NAMES
> 84d2a565793c    docker.io/kubeedge/pause:3.6    "/pause"    About an hour ago    Created
2. rm container:
`$ nerdctl rm 84d2a565793ce8ed658488500612287840f4a81225491611c1ee21dc7f4162cc --namespace k8s.io`
>84d2a565793ce8ed658488500612287840f4a81225491611c1ee21dc7f4162cc

**Comment by fisherxu** [comment] 2023-07-27 01:26
> 我也遇到了相同的问题，请问怎么解决的？ execute keadm command failed: edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to reserve sandbox name "edgecore_kubeedge__0": name "edgecore_kubeedge__0" is reserved for "42bde66aa0bdb259a8244ea7b3695642e6615825c70cfe69e567fd9528565768"


1. First please check whether the CNI is well installed for contained.
2. Try restart `cintainerd` system service, then try to install kubeedge.

If it's still failed, try to:
1. Use `ctr` or `nerdctl` or other tools to remove all tasks and containers.
```
ctr -n k8s.io t ls
ctr -n k8s.io t del TASK-ID

ctr -n k8s.io c ls
ctr -n k8s.io c del CONTAINER-ID
```
2. Try restart `cintainerd` system service, then try to install kubeedge.

**Comment by fisherxu** [comment] 2023-07-27 01:28
/close

Please reopen it if needed :)

**Closed by fisherxu** 2023-07-27 01:28 UTC
Labels: kind/question

**Comment by zhuyaguang** [comment] 2023-11-07 03:00
https://developer.aliyun.com/article/1194231 add flag --runtimetype=docker

**Comment by shawn-robusoft** [comment] 2023-12-03 11:43
最后咋解决的，我在K8S v1.26.7 ，Kubeedge v1.15.1 上也遇到这个问题。K8S集群使用的flannel网络插件，使用的是containerd运行时。

**Comment by shawn-robusoft** [comment] 2023-12-03 11:45
> 2\. cintainerd

咋解决的

**Comment by bluven** [comment] 2023-12-04 07:55
一个问题反复出现，官方为什么不给个解决方案？官网安装教程还是1.12.1的，现在1.15都出来了，延迟太高了吧

**Comment by davidleecn** [comment] 2023-12-07 04:33
cCI6IkpXVCJ9.eyJleHAiOjE3MDE5MDQyOTh9.AK79ltdRyjVqeWrToEekWtGkZoJ9Ba4Iwo64aGUrjfY
I1207 12:30:10.404452   21029 command.go:901] 1. Check KubeEdge edgecore process status
I1207 12:30:10.407984   21029 command.go:901] 2. Check if the management directory is clean
I1207 12:30:10.408031   21029 join.go:107] 3. Create the necessary directories
I1207 12:30:10.410522   21029 join.go:184] 4. Pull Images
Pulling docker.io/kubeedge/installation-package:v1.15.1 ...
Successfully pulled docker.io/kubeedge/installation-package:v1.15.1
Pulling docker.io/library/eclipse-mosquitto:1.6.15 ...
Successfully pulled docker.io/library/eclipse-mosquitto:1.6.15
Pulling docker.io/kubeedge/pause:3.6 ...
Successfully pulled docker.io/kubeedge/pause:3.6
I1207 12:30:10.412783   21029 join.go:184] 5. Copy resources from the image to the management directory
E1207 12:30:10.421757   21029 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"172c4dfd95dab83ce37575eb60c404611787b31abd3b348fe502cd3df3dc976f\": cni plugin not initialized"
Error: edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to setup network for sandbox "172c4dfd95dab83ce37575eb60c404611787b31abd3b348fe502cd3df3dc976f": cni plugin not initialized
execute keadm command failed:  edge node join failed: copy resources failed: rpc error: code = Unknown desc = failed to setup network for sandbox "172c4dfd95dab83ce37575eb60c404611787b31abd3b348fe502cd3df3dc976f": cni plugin not initialized

--------
遇到同样的错误，kubeedge是最新稳定版v1.15.1，k8s是v1.26.4，官方文档并未说明需要提前安装cni等

**Comment by Mrzzzzz** [comment] 2023-12-21 01:28
> 最后咋解决的，我在K8S v1.26.7 ，Kubeedge v1.15.1 上也遇到这个问题。K8S集群使用的flannel网络插件，使用的是containerd运行时。

resolve？

**Comment by luomengY** [comment] 2023-12-23 08:58
> The installation process of kubedge is decoupled from the CNI plugin and will be supported in future versions（ #5196 ）However, it is only during the installation process that CNI plugins are not required. If kubedge is deployed, CNI plugins such as Flannel still need to be installed like k8s.

The installation process of kubedge is decoupled from the CNI plugin and will be supported in future versions（ https://github.com/kubeedge/kubeedge/pull/5196 ）However, it is only during the installation process that CNI plugins are not required. If kubedge is deployed, CNI plugins such as Flannel still need to be installed like k8s.

**Comment by luomengY** [comment] 2023-12-23 08:59
> > 最后咋解决的，我在K8S v1.26.7 ，Kubeedge v1.15.1 上也遇到这个问题。K8S集群使用的flannel网络插件，使用的是containerd运行时。
> 
> resolve？

1.Use ctr or nerdctl or other tools to remove all tasks and containers.
ctr -n k8s.io t ls
ctr -n k8s.io t del TASK-ID

ctr -n k8s.io c ls
ctr -n k8s.io c del CONTAINER-ID
2.Try restart cintainerd system service, then try to install kubeedge.

**Comment by luomengY** [comment] 2023-12-23 09:00
> > 最后咋解决的，我在K8S v1.26.7 ，Kubeedge v1.15.1 上也遇到这个问题。K8S集群使用的flannel网络插件，使用的是containerd运行时。
> 
> resolve？

The installation process of kubedge is decoupled from the CNI plugin and will be supported in future versions（ #5196 ）However, it is only during the installation process that CNI plugins are not required. If kubedge is deployed, CNI plugins such as Flannel still need to be installed like k8s.
