### ISSUE TITLE
Modbus_mapper Pod Start Failture

### ISSUE THREAD

**Issue by liyongxian** [kubeedge/kubeedge#918] opened 2019-07-16 10:40 UTC
****What happened**:**
After Create Device Instance by DeviceModel,and the device is connected to edge node.When kubectl apply -f deployment.yaml,the pod start failture.
**What you expected to happen**:
The Pod of modbus-mapper running
**How to reproduce it (as minimally and precisely as possible)**:
1.devicemodel and device
create-device-model.yaml and create-device-instance.yaml
2.modbus_app
kubectl create -f deployment.yaml
main refer to :
https://kubeedge.readthedocs.io/en/v1.0.0/mappers/modbus_mapper.html
**Anything else we need to know?**:

**Environment**:
- KubeEdge version:

NAME          STATUS   ROLES                      AGE    VERSION
edge-node-1   Ready    edge                       3d4h   v1.10.9-kubeedge-0.3.0
edge-node-2   Ready    edge                       28h    v1.10.9-kubeedge-0.3.0
master-1      Ready    controlplane,etcd,worker   3d5h   v1.13.5

- Hardware configuration:
- OS (e.g. from /etc/os-release):
ubuntu 16.04.5 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`):
Linux master-1 4.4.0-131-generic
- Others:
**modbus-mapper container error info:**

CONNECTOR_MQTT_IP=127.0.0.1
CONNECTOR_MQTT_PORT=1883
[2019-07-16T10:14:57.103] [INFO] appenders - start to watch dpl config
[2019-07-16T10:14:57.116] [INFO] appenders - start to check devicetwin state
[2019-07-16T10:14:57.209] [INFO] appenders - start to wait for devicetwin update
[2019-07-16T10:14:57.217] [INFO] appenders - connetced to edge mqtt with topic twinGet
[2019-07-16T10:14:57.223] [INFO] appenders - connetced to edge mqtt with topic twinDelta
[2019-07-16T10:14:59.120] [INFO] appenders - chechking devicetwin state
**/opt/src/node_modules/bindings/bindings.js:121
        throw e;
        ^**

Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (/opt/src/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/opt/src/node_modules/@serialport/bindings/lib/linux.js:1:36)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

Thanks.

**Comment by sids-b** [comment] 2019-07-18 06:06
@RicardoZPHuang can you please take a look ?

**Comment by RicardoZPHuang** [comment] 2019-07-18 06:53
@liyongxian it looks like a build problem when using npm install to download the node_modules. Could u please tell me the version of npm?  If u updated the npm, u can try `rm -rf node_modules` in `kubeedge/device/modbus_mapper/src` and rebuild the image by `make`

**Comment by liyongxian** [comment] 2019-07-19 01:42
@RicardoZPHuang 
**node -v**   
  v6.17.1

**npm -v**   
  3.10.10

Thanks.

**Comment by liyongxian** [comment] 2019-07-19 01:56
@sids-b @RicardoZPHuang 
I have done as what @RicardoZPHuang said. **"rm -rf node_modules in kubeedge/device/modbus_mapper/src and rebuild the image by make"**. but it is **wrong**. The problem is the same.
Thanks a lot.

**Comment by RicardoZPHuang** [comment] 2019-07-19 03:11
@liyongxian The container works fine with node version 10.15 and npm version 6.9.0 here. Could u please try to upgrade ur node/npm to higher version like node 10.15 and npm 6.9? Since the node version using in images is 10.16. I think maybe we should move `npm install ` process in docker build rather than copy the node_modules into images.

**Comment by liyongxian** [comment] 2019-07-19 04:06
@RicardoZPHuang  When I upgraded node/npm to  node 10.16.0 and npm 6.10.1,that problem is gone.**But the container can not start.**
**Error info:**
CONNECTOR_DPL_NAME=dpl/deviceProfile.json
CONNECTOR_MQTT_IP=127.0.0.1
CONNECTOR_MQTT_PORT=1883
[2019-07-19T03:57:02.701] [INFO] appenders - start to watch dpl config
[2019-07-19T03:57:02.710] [INFO] appenders - start to check devicetwin state
[2019-07-19T03:57:02.789] [INFO] appenders - start to wait for devicetwin update
[2019-07-19T03:57:02.797] [INFO] appenders - connetced to edge mqtt with topic twinGet
[2019-07-19T03:57:02.800] [INFO] appenders - connetced to edge mqtt with topic twinDelta
[2019-07-19T03:57:04.713] [INFO] appenders - **chechking devicetwin state**
**Segmentation fault (core dumped)** 
How Can I Do?
Thanks.

**Comment by RicardoZPHuang** [comment] 2019-07-19 04:17
@liyongxian Did u use the ModbusRTU protocol to connect device with serial ports not open or wrong serial ports? Could u please provide the create-device-instance.yaml？

**Comment by liyongxian** [comment] 2019-07-19 06:17
@RicardoZPHuang  **create-device-instance.yaml Info:**

apiVersion: devices.kubeedge.io/v1alpha1
kind: Device
metadata:
  name: sensor-tag-instance-01
  labels:
    description: TISimplelinkSensorTag
    manufacturer: TexasInstruments
    model: CC2650
spec:
  deviceModelRef:
    name: sensor-tag-model
  protocol:
    modbus:
      rtu:
        **serialPort: '1'**
        baudRate: 115200
        dataBits: 8
        parity: even
        stopBits: 1
        slaveID: 1
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: ''
        operator: In
        values:
        - node1
status:
  twins:
    - propertyName: temperature-enable
      reported:
        metadata:
          timestamp: '1550049403598'
          type: string
        value: 'OFF'
      desired:
        metadata:
          timestamp: '1550049403598'
          type: string
        value: 'OFF'

Thanks.

**Comment by RicardoZPHuang** [comment] 2019-07-19 06:54
@liyongxian this sample yaml is using rtu protol with serial ports 1, which should be some thing like `/dev/ttyUSB0`  in linux or `COM1` in windows. And also the device(simulator) should be connected to the serial port. If u want to try modbusTCP protocol, u can replace the rtu part with following tcp config.
tcp:
prot: 5020
ip: "127.0.0.1"
slaveID: "1"

**Comment by liyongxian** [comment] 2019-07-19 09:22
@RicardoZPHuang  Sorry,The Pod of modbus_mapper can NOT run well.

**Device-instance config:**
tcp:
        port: 5020
        ip: "127.0.0.1"
        baudRate: 115200
        dataBits: 8
        parity: even
        stopBits: 1
        slaveID: "1"

**The Pod info:**
NAME                                           READY            STATUS                    RESTARTS                        AGE
modbus-device-mapper-deployment-84b47f6c9c-5mztc   0/1     **ContainerCreating**   0          14m

the contain's status is **ContainerCreating**, and describe the Pod info:
 **Normal  Scheduled  12m   default-scheduler  Successfully assigned edge/modbus-device-mapper-deployment-84b47f6c9c-5mztc to edge-node-2**
Thanks.

**Comment by RicardoZPHuang** [comment] 2019-07-19 09:59
@liyongxian for tcp it only contains port, ip and slaveID. The baudRate, dataBits, parity, stopBits is for rtu. The whole yaml should be the following.
apiVersion: devices.kubeedge.io/v1alpha1
kind: Device
metadata:
name: sensor-tag-instance-01
labels:
description: TISimplelinkSensorTag
manufacturer: TexasInstruments
model: CC2650
spec:
deviceModelRef:
name: sensor-tag-model
protocol:
modbus:
tcp:
prot: 5020
ip: "127.0.0.1"
slaveID: "1"
nodeSelector:
nodeSelectorTerms:
- matchExpressions:
- key: ''
operator: In
values:
- node1
status:
twins:
- propertyName: temperature-enable
reported:
metadata:
timestamp: '1550049403598'
type: string
value: 'OFF'
desired:
metadata:
timestamp: '1550049403598'
type: string
value: 'OFF'

**Comment by liyongxian** [comment] 2019-07-19 10:22
@RicardoZPHuang  I am so Sorry.  The Pod of modbus_mapper can NOT run well,and its status is **ContainerCreating**
Device-instance config:
![edge-nodejpeg](https://user-images.githubusercontent.com/18571576/61528490-857ac800-aa51-11e9-9823-75e64d9a3972.jpg)

Thanks a lot.

**Comment by liyongxian** [comment] 2019-07-19 10:24
**Describe the Pod:**

![QQ截图20190719182326](https://user-images.githubusercontent.com/18571576/61528848-6c264b80-aa52-11e9-880f-c91832b09c28.jpg)

**Comment by RicardoZPHuang** [comment] 2019-07-19 11:24
@liyongxian ok seems the problem is starting container in edge_core. could u please search the log with `cat edge_core.log | grep modbus-device-mapper-deployment | grep edged.go` ?

**Comment by liyongxian** [comment] 2019-07-20 04:43
@RicardoZPHuang Thanks. The Pod's status is running now. After I restart the edge_core,delete the deployment and create it again. The pod is  running. It is amazing.I do not know  why ?

**Comment by RicardoZPHuang** [comment] 2019-07-20 05:55
@liyongxian well, if the pod status is containerCreating, it could be in processing of image pulling or volume mounting. Maybe we can find out the reason by searching log as I said above. `cat edge_core.log | grep modbus-device-mapper-deployment | grep edged.go` can show if there are some problem creating container.

**Comment by liyongxian** [comment] 2019-07-22 03:37
@RicardoZPHuang The Pod of modbus_mapper is running now.but its container log info:
[2019-07-22T03:26:58.952] [INFO] appenders - chechking devicetwin state
[2019-07-22T03:26:58.953] [ERROR] appenders - failed to update devicetwin[temperature] of device[sensor-tag-instance-01], err:  **PortNotOpenError {
  name: 'PortNotOpenError',
  message: 'Port Not Open',
  errno: 'ECONNREFUSED' }**

The device-instance  uses tcp communication protocol to device  in modbus_mapper,Port is 5020. But the port does not exist in edge node, and how I configure  the port (5020). 
Thanks.

**Comment by RicardoZPHuang** [comment] 2019-07-22 04:26
@liyongxian this port indicate the device port. u need to set ur modbus device or simulator with port 5020. For example, modbus slave simulator.

**Comment by liyongxian** [comment] 2019-07-22 06:49
@RicardoZPHuang  I can not find anything about **modbus slave simulator** in  KubeEdge, and how can I do? I Need Your Help.
Thanks.

**Comment by liyongxian** [comment] 2019-07-22 10:08
@RicardoZPHuang   The  container of  modbus_mapper docker  log info:
[2019-07-22T09:46:15.881] [INFO] appenders - chechking devicetwin state
[2019-07-22T09:46:15.885] [INFO] appenders - update devicetwin[temperature] of device[sensor-tag-instance-01] successfully
[2019-07-22T09:46:16.386] **[ERROR] appenders - failed to update devicetwin[temperature-enable] of device[sensor-tag-instance-01], err:  TransactionTimedOutError {
  name: 'TransactionTimedOutError',
  message: 'Timed out',
  errno: 'ETIMEDOUT' }**

The ENV in deployment.yaml :
![edge00](https://user-images.githubusercontent.com/18571576/61624640-9292f380-acab-11e9-9c3d-89a62a4a29df.jpg)

Thanks.

**Comment by RicardoZPHuang** [comment] 2019-07-22 14:56
@liyongxian modbus slave simulator:https://www.modbustools.com/modbus_slave.html .
Does the property "temperature-enable" config in device-instance.yaml match the config in simulator?

**Comment by sids-b** [comment] 2019-08-31 08:01
@liyongxian , is this issue resolved ?

**Comment by sids-b** [comment] 2019-09-11 06:45
Closing this issue. Please feel free to reopen or reach out to us via slack for further discussions

**Closed by sids-b** 2019-09-11 06:45 UTC
Labels: kind/bug
