### ISSUE TITLE
run `kubectl logs` failure

### ISSUE THREAD

**Issue by jayce** [kubeedge/kubeedge#3197] opened 2021-09-24 06:22 UTC
**What happened**:
I run `kubectl logs -f nginx-deployment-599b9698d8-qf4dc` on the masterNode
`Error from server: Get https://10.229.1.109:10350/containerLogs/default/nginx-deployment-599b9698d8-qf4dc/nginx?follow=true: dial tcp 10.229.1.109:10350: connect: connection refused`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. keadm reset
2. upgrade to v1.8.0

**Anything else we need to know?**:
edge side: In code , the stream's port is 10350 always.
https://github.com/kubeedge/kubeedge/blob/28306dd045606b74eb9dd26872998ad01e5e85cf/edge/pkg/edged/server/server.go#L36

cloud side: In code , the port always is 10351, that I think it's a bug.
https://github.com/kubeedge/kubeedge/blob/28306dd045606b74eb9dd26872998ad01e5e85cf/cloud/cmd/cloudcore/app/server.go#L223-L228

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.18.20`
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): `KubeEdge v1.8.0`

**Comment by fisherxu** [comment] 2021-09-24 07:45
Can you please check the port in `node.status/daemonEndpoints`, it should be `10351`. @jayce 

```
kubectl get nodes YOUR-NODE -oyaml
```

**Comment by jayce** [comment] 2021-09-24 10:06
> Can you please check the port in `node.status/daemonEndpoints`, it should be `10351`. @jayce
> 
> ```
> kubectl get nodes YOUR-NODE -oyaml
> ```

edgenode:

```yaml
...
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10350
...
```

**Comment by fisherxu** [comment] 2021-09-26 04:00
> cloud side: In code , the port always is 10351, that I think it's a bug.

It's not a bug, for multi-cloudcore, the ports in cloudcore will be 10351,10352..  And the `kubeletEndpoint` should be 10351. I think it's because the configmap `kubectl get cm tunnelport -nkubeedge` haven't been deleted when reset, so the `kubeletEndpoint` is 10350 in your cluster.

ref: https://github.com/kubeedge/kubeedge/issues/1560#issuecomment-843693951

**Comment by jayce** [comment] 2021-09-27 08:58
okay , it works when I restart the edgecore.

Since 1.8.0, the default of kubeletEndpoint is 10351, not 10350?

**Comment by fisherxu** [comment] 2021-09-27 09:09
> okay , it works when I restart the edgecore.
> 
> Since 1.8.0, the default of kubeletEndpoint is 10351, not 10350?

In edged, it's 10350. And for cloudcore we will negotiate one port for one cloudcore instance, e.g. cloudcore1: 10351, cloudcore2: 10352...

And when edgenode connects to one cloudcore, the port in `kubeletEndpoint`/`nodestatus` will be updated to the port that cloudcoreN negotiated.

And we will also add some iptable rules that forward stream from apiserver to cloudcore.  Then 10351 ->  cloudcore1, 10352 -> cloudcore2.

And if we use 10350 in  `kubeletEndpoint`/`nodestatus`, we don’t know which cloudcore instance to forward to.

**Comment by fisherxu** [comment] 2021-11-23 08:22
Close the issue, free to reopen it if there's any problem.
/close

**Closed by fisherxu** 2021-11-23 08:22 UTC
Labels: kind/bug
