### ISSUE TITLE
Failed to unmarshal configfile /etc/kubeedge/config/edgecore.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Edged.modules.edged.volumeStatsAggPeriod of type time.Duration

### ISSUE THREAD

**Issue by yzhao66** [kubeedge/kubeedge#1707] opened 2020-05-20 10:24 UTC
**What happened**:
when i  vim /var/log/kubeedge/edgecore.log 
show" Failed to unmarshal configfile /etc/kubeedge/config/edgecore.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Edged.modules.edged.volumeStatsAggPeriod of type time.Duration
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Edged.modules.edged.volumeStatsAggPeriod of type time.Duration"

![image](https://user-images.githubusercontent.com/44268973/82435252-9a3b4880-9ac6-11ea-985e-cab026657823.png)

and get nodes on master,there is no edgenode name
![image](https://user-images.githubusercontent.com/44268973/82435294-aaebbe80-9ac6-11ea-9316-e7678d89d6c7.png)

**What you expected to happen**:

can get edgenode and no bug show in edgecore.log file

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
1.3.0
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):ubuntu
- Kernel (e.g. `uname -a`):Linux kube-cloudserver 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): go version go1.13.11 linux/amd64
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):1.3.0
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):ubuntu
- Kernel (e.g. `uname -a`):go version go1.13.11 linux/amd64
- Go version (e.g. `go version`): go version go1.13.11 linux/amd64
- Others:

**Comment by luogangyi** [comment] 2020-05-20 13:10
Duplicate of #1694

**Comment by fisherxu** [comment] 2020-05-21 09:18
The issue has been fixed in #1701, for workaround you can compile a keadm from master branch, and we will release the fix in 1.3.1
/close

**Closed by fisherxu** 2020-05-21 09:18 UTC
Labels: kind/bug
