### ISSUE TITLE
Errors occur when try to build KubeEdge on mac

### ISSUE THREAD

**Issue by SpaghettiAndSalmon** [kubeedge/kubeedge#1064] opened 2019-08-22 16:31 UTC
**What happened**:
Follow the doc(https://docs.kubeedge.io/en/latest/setup/setup.html) to set up KubeEdge.
Errors occur in step _Build Cloud and edge_ .
```
cd $GOPATH/src/github.com/kubeedge/kubeedge
make
```
Errors:
```
cd cloud && /Library/Developer/CommandLineTools/usr/bin/make
go build cmd/cloudcore/cloudcore.go
cd edge && /Library/Developer/CommandLineTools/usr/bin/make
go build cmd/edgecore/edgecore.go
pkg/edged/edged.go:88:2: build constraints exclude all Go files in $GOPATH/src/github.com/kubeedge/kubeedge/edge/pkg/edged/cadvisor
make[1]: *** [edgecore] Error 1
make: *** [all] Error 2
```
**What you expected to happen**:
successful build.
**How to reproduce it (as minimally and precisely as possible)**:
Please see the details in part _What happened_.
**Environment**:
- KubeEdge version: 
the latest from the master branch.
- Hardware configuration: 
mackbook pro(15-inch, Mid 2015)
- OS :
macOS Sierra.
- Kernel :
```
Darwin bogon 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64
```
- Others:
```
gcc --version
```
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
```
go version
```
```
go version go1.12.5 darwin/amd64
```

**Comment by subpathdev** [comment] 2019-08-27 21:12
> ```
> gcc --version
> Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> Apple LLVM version 8.0.0 (clang-800.0.38)
> Target: x86_64-apple-darwin16.7.0
> Thread model: posix
> InstalledDir: /Library/Developer/CommandLineTools/usr/bin
> ```

As you can see, you are not using gcc. You are using clang as C compiler. Perhaps you can use this to compile on macOS:
https://go.googlesource.com/gollvm/

**Comment by joeblew99** [comment] 2019-08-29 11:09
also tinygo can be used instead of gollvm

https://github.com/tinygo-org/tinygo
https://news.ycombinator.com/item?id=20474530

Its also great for building IOT software

**Comment by sids-b** [comment] 2019-09-11 06:57
@SpaghettiAndSalmon Is this issue resoled ?

**Comment by sids-b** [comment] 2019-09-27 10:19
Closing this issue. Please feel free to reachout on slack or reopen for further discussion :)

**Closed by sids-b** 2019-09-27 10:19 UTC
Labels: kind/bug

**Comment by zshwei** [comment] 2021-06-17 16:29
Hi there,
 Trying to build from MacOS. Is this also caused by the gcc ? 

------------------------------------------
_weizha03@C02ZQ0KYLVDM kubeedge % make all WHAT=cloudcore
hack/verify-golang.sh
go detail version: go version go1.16.5 darwin/amd64
go version: 1.16.5
KUBEEDGE_OUTPUT_SUBPATH=_output/local hack/make-rules/build.sh cloudcore
make: *** [all] Error 1


weizha03@C02ZQ0KYLVDM kubeedge % gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin_
