### ISSUE TITLE
undefined: ContainerManager - Building edge_core on MacOS

### ISSUE THREAD

**Issue by priyankt68** [kubeedge/kubeedge#292] opened 2019-03-24 07:21 UTC
Hi everyone,

I am trying to build edge_core on MacOS. I am facing following issue while building it.

**What happened**:

```
$ make edge_core
go build cmd/edge_core.go
# github.com/kubeedge/kubeedge/edge/pkg/edged/containers
pkg/edged/containers/helpers.go:114:33: undefined: ContainerManager
pkg/edged/containers/helpers.go:129:10: undefined: containerManager
make: *** [edge_core] Error 2
```

**How to reproduce it (as minimally and precisely as possible)**:
Clone KubeEdge repository on MacOS.
```
git clone git@github.com:priyankt68/kubeedge.git $GOPATH/src/github.com/kubeedge/kubeedge
cd $GOPATH/src/github.com/kubeedge
```

Do I need to do anything else before I build edge_core ?

I do have Docker daemon running on MacOS.
```
$ docker --version
Docker version 18.09.2, build 6247962
```

**Environment**:
- KubeEdge version: latest from master branch
- System Config - 
```
$ uname -a
Darwin Priyanks-MBP-d06f 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

**Comment by m1093782566** [comment] 2019-03-24 08:24
I think you need to cross-build kubeedge(at least edge-core) with Darwin arch.

**Comment by sids-b** [comment] 2019-03-24 13:33
If anyone has tried KubEdge on MAC, please help solve this issues :)

**Comment by nkwangleiGIT** [comment] 2019-03-24 14:07
I don't think edge-core can run on Mac, but you can compile it on Mac using command below:
```
 env GOOS=linux GOARCH=amd64 go build cmd/edge_core.go
```
and copy it to linux, then run it following the KubeEdge instructions.

The error above was caused by container_manager.go, as it has build constraint declared in the file header.
'''
// +build linux
'''

**Comment by rohitsardesai83** [comment] 2019-03-25 17:38
cc @Baoqiang-Zhang , is it possible to remove this constraint in container_manager.go ? or we currently limit to only linux ?

**Comment by gklp** [comment] 2019-03-25 19:13
> GOOS=linux GOARCH=amd64 go build cmd/edge_core.go

That approach resolves that isssue. I think that  /edge/Makefile should be improved with os and arch. cross_build can be good point to change.

**Comment by priyankt68** [comment] 2019-03-26 06:05
> GOOS=linux GOARCH=amd64 go build cmd/edge_core.go

Thanks @nkwangleiGIT. I did try and it created a binary. I understand that I will have to run this binary in any linux environment. I will try this out in a RaspberryPi.

@gklp I would like to help out with this. I understand from your comment that some changes might be required to [this](https://github.com/kubeedge/kubeedge/blob/8f4ceaee09e09fe3cd575db325e32df98b65391a/edge/Makefile#L33) line. 

I am new to Golang and therefore might need more help from community. I do have Go setup already done in my machine.

From what I also understand, Golang by default supports values in `GOOS` and `GOARCH` detailed in this [gist](https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63).

**Comment by gklp** [comment] 2019-03-29 05:49
> > GOOS=linux GOARCH=amd64 go build cmd/edge_core.go
> 
> Thanks @nkwangleiGIT. I did try and it created a binary. I understand that I will have to run this binary in any linux environment. I will try this out in a RaspberryPi.
> 
> @gklp I would like to help out with this. I understand from your comment that some changes might be required to [this](https://github.com/kubeedge/kubeedge/blob/8f4ceaee09e09fe3cd575db325e32df98b65391a/edge/Makefile#L33) line.
> 
> I am new to Golang and therefore might need more help from community. I do have Go setup already done in my machine.
> 
> From what I also understand, Golang by default supports values in `GOOS` and `GOARCH` detailed in this [gist](https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63).

Exactly, the gist link is very useful.

**Comment by sids-b** [comment] 2019-04-14 07:17
@priyankt68 , is this issue resolved ? Can we close this issue ?

**Comment by m1093782566** [comment] 2019-04-14 07:19
@sids-b 

Before closing this issue, we should add `darwin` support in the cross-build job.

**Comment by sids-b** [comment] 2019-04-14 07:31
+1 @srivatsav123 , please help with this, Thanks

**Comment by rohitsardesai83** [comment] 2019-05-07 05:46
@srivatsav123 , can you please take  a look at this ?

**Comment by srivatsav123** [comment] 2019-05-07 07:23
@rohitsardesai83 -ok

**Comment by srivatsav123** [comment] 2019-05-07 07:31
@priyankt68 :Hi , Please follow the below steps and build it (this steps are cross compilation of edge_core to support mac)
export GOARCH=amd64
        export GOOS=darwin
        export GOCHAR=6
        export GOHOSTARCH=darwin
        export CGO_ENABLED=1
        export CC=gcc

        go build cmd/edge_core.go(i used go version go1.12.4 linux/amd64 for cross compilation)
Please export these env variables and build it in ubuntu system..Then transfer the binary to your macos and test it..Since i dont have macos supported system i didnot test it..
Please give a try and let me know..

**Comment by priyankt68** [comment] 2019-05-07 18:34
@srivatsav123 Sure. Will try it out and get back here.

**Comment by sids-b** [comment] 2019-05-10 13:46
Hi @priyankt68 , were you able to run KubeEdge on MacOS

**Comment by priyankt68** [comment] 2019-05-11 12:23
Here are the results for my run on an Ubuntu machine. @srivatsav123 @sids-b 

#### Exporting environment variables for cross compiling
```
$ ~/go/src/github.com $ export GOARCH=amd64
export GOOS=darwin
export GOCHAR=6
export GOHOSTARCH=darwin
export CGO_ENABLED=1
export CC=gcc
```

#### Build edge_core in Ubuntu
```
 $ ~/go/src/github.com/kubeedge/kubeedge/edge $ go build cmd/edge_core.go
# net
/usr/local/go/src/net/cgo_bsd.go:15:72: could not determine kind of name for C.AI_MASK
# github.com/kubeedge/kubeedge/vendor/github.com/mattn/go-sqlite3
/tmp/go-build465143713/b102/_x011.o: In function `unixDlError':
../vendor/github.com/mattn/go-sqlite3/sqlite3-binding.c:37959: undefined reference to `dlerror'
/tmp/go-build465143713/b102/_x011.o: In function `unixDlClose':
../vendor/github.com/mattn/go-sqlite3/sqlite3-binding.c:37990: undefined reference to `dlclose'
/tmp/go-build465143713/b102/_x011.o: In function `unixDlSym':
../vendor/github.com/mattn/go-sqlite3/sqlite3-binding.c:37986: undefined reference to `dlsym'
/tmp/go-build465143713/b102/_x011.o: In function `unixDlOpen':
../vendor/github.com/mattn/go-sqlite3/sqlite3-binding.c:37945: undefined reference to `dlopen'
collect2: error: ld returned 1 exit status
# os/user
/usr/local/go/src/os/user/getgrouplist_darwin.go: In function 'mygetgrouplist':
/usr/local/go/src/os/user/getgrouplist_darwin.go:16:11: warning: implicit declaration of function 'getgrouplist'; did you mean 'mygetgrouplist'? [-Wimplicit-function-declaration]
  int rv = getgrouplist(user, (int) group, buf, ngroups);
           ^~~~~~~~~~~~
           mygetgrouplist
```

**Comment by srivatsav123** [comment] 2019-05-13 15:20
yes..i too faced..
I just referred the blog,It says
we have to create **OS X cross compiler tool chain**.To build the edge_core for mac(darwin)
If time permits please refer this blog
**https://rwalk.xyz/rust-cross-compiling-from-ubuntu-to-os-x/**
I tried but,ended up in vain since i dont have valid apple login account to download **Xcode_7.3.1.dmg**.....!!

**Comment by sids-b** [comment] 2019-06-01 06:46
This issue is similar to #634 and PR #635 fixes it. Closing this issue

**Comment by m1093782566** [comment] 2019-06-01 06:46
Please check: #635

**Closed by sids-b** 2019-06-01 06:46 UTC
Labels: good first issue, kind/bug
